package dev.ruleblend.core.integration

import java.nio.file.Path

/**
 * How an agent is started from a terminal. Ruleblend installs the instructions an agent reads; the
 * CLI is the other half of the same act — a project is set up so that work can start in it, and the
 * shortest way from "set up" to "working" is one click.
 */
data class AgentCli(
    /** Executable name, resolved through the user's login shell rather than the app's stunted PATH. */
    val executable: String,
    /** Arguments that pick up the agent's last session in this directory; `null` when it cannot. */
    val resumeArguments: List<String>? = null,
)

/** Which session a launch asks for. */
enum class AgentLaunchMode { NEW, RESUME }

/**
 * A launcher is a small shell script rather than a direct spawn: it is what makes the agent land in
 * a real terminal the user can type into, and it is handed to the terminal the same way a document
 * is handed to its application.
 *
 * The command runs through the user's own login shell (interactive when the executable was only
 * found that way), because a CLI installed by nvm, mise or Homebrew is on the PATH the shell builds,
 * not on the one a bundled macOS app inherits — and the agent itself re-reads that PATH when it
 * spawns `node`.
 */
object AgentLauncherScript {

    /**
     * The script text: one `exec` into the login shell, which changes into [directory] and replaces
     * itself with the agent, so the terminal window belongs to the agent and closes when it exits.
     */
    fun render(
        shell: String,
        directory: Path,
        command: List<String>,
        interactive: Boolean,
    ): String {
        val inner = "cd ${shellQuote(directory.toString())} && exec ${command.joinToString(" ") { shellQuote(it) }}"
        val flags = if (interactive) "-ilc" else "-lc"
        return buildString {
            appendLine("#!/bin/sh")
            appendLine("# Generated by Ruleblend. Rewritten on every launch; safe to delete.")
            appendLine("exec ${shellQuote(shell)} $flags ${shellQuote(inner)}")
        }
    }

    /**
     * File name for the launcher of [agentId] in [directory]. The project name leads, because it is
     * what the terminal puts in its window title; the digest keeps two checkouts of the same name
     * apart, and keeps the launcher directory from growing with every click.
     */
    fun fileName(agentId: String, directory: Path): String {
        val project = directory.fileName?.toString().orEmpty().lowercase()
            .map { if (it.isLetterOrDigit() || it == '-' || it == '_') it else '-' }
            .joinToString("")
            .trim('-')
            .ifEmpty { "project" }
        return "$project-$agentId-${digest(directory.toString())}.command"
    }

    /** Single-quoted for `sh`: a path with spaces, `$` or `!` survives; an embedded quote is escaped. */
    private fun shellQuote(value: String): String = "'" + value.replace("'", "'\\''") + "'"

    private fun digest(value: String): String {
        val bytes = java.security.MessageDigest.getInstance("SHA-256").digest(value.encodeToByteArray())
        return bytes.take(4).joinToString("") { "%02x".format(it) }
    }
}

/**
 * Splits a user-typed argument line the way a shell would, honouring single and double quotes so
 * `--append-system-prompt "be brief"` stays two arguments rather than three. Deliberately not a
 * shell: no expansion, no substitution — what is typed is what the agent is given.
 */
fun splitArguments(line: String): List<String> {
    val arguments = mutableListOf<String>()
    val current = StringBuilder()
    var quote: Char? = null
    var started = false
    for (character in line) {
        when {
            quote != null && character == quote -> quote = null
            quote != null -> current.append(character)
            character == '\'' || character == '"' -> { quote = character; started = true }
            character.isWhitespace() -> {
                if (started || current.isNotEmpty()) arguments += current.toString()
                current.clear()
                started = false
            }
            else -> current.append(character)
        }
    }
    if (started || current.isNotEmpty()) arguments += current.toString()
    return arguments
}

/** The full command line for [cli] in [mode], with the user's extra arguments last. */
fun agentCommand(cli: AgentCli, mode: AgentLaunchMode, extraArguments: String): List<String> {
    val session = when (mode) {
        AgentLaunchMode.NEW -> emptyList()
        AgentLaunchMode.RESUME -> cli.resumeArguments.orEmpty()
    }
    return listOf(cli.executable) + session + splitArguments(extraArguments)
}
